version: '3'
services:
  redis:
    container_name: cache_redis
    image: redis
    #  command: redis-server --requirepass Redis2020
    # volumes:
    #   - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
